### ISSUE TITLE
Merci pour cette API

### ISSUE THREAD

**Issue by clorl** [sin0light/api-kaamelott#1]
Je ne pensais pas qu'elle existait, je suis heureux de la voir.

Je vais créer une extension Nextcloud utilisant cette API

**Comment by sin0light** [comment]
Hello,

Aucun problème ! Je vais m'empresser de l'enrichir puisqu'elle a l'air de plaire !

**Comment by celine-m-s** [comment]
Salut ! Je voulais juste dire merci aussi ! Cette API est une excellente idée. <3
