### ISSUE TITLE
Dépôt de `kaamelottbot` ?

### ISSUE THREAD

**Issue by Geobert** [sin0light/api-kaamelott#10]
Bonjour, 

trop drôle cette API merci !

Je me demandais où poser des questions concernant le bot `kaamelottbot` qui est donné sur la page d’accueil ?

Genre comment faire pour insérer une citation dans un tchat (pas un groupe, ça j’ai trouvé) ? On peut insérer un son depuis n’importe quel tchat avec `@kaamelottbot` mais pas de citation on dirait

**Comment by sin0light** [comment]
Hello,

Merci ! Oui tu peux poser ici pas de problème.

Argh malheureusement ce n'est pas possible ... La seule méthode est d'ajouter le bot à la conversation (donc de passer d'un tchat à un groupe de 2 personnes + un bot) mais je comprends bien que ce n'est pas idéal ...
A ma connaissance, Telegram ne permet pas ce type d'action mais hésite pas à me donner un exemple si tu en as un !

Sin0light

**Comment by Geobert** [comment]
Je me demande si on ne pourrait pas se servir de `@kaamelottbot` pour ça aussi, genre `@kaamelottbot /perso leodagan <requete>` et pour garder le soundboard : `@kaamelottbot /sound <requete>` 

mais c’est peut être beaucoup d’effort pour pas grand chose ^^'

**Comment by sin0light** [comment]
Malheureusement, Telegram ne permet pas cela ...

**Comment by sin0light** [comment]
Malheureusement, Telegram ne permet pas cela ...

**Comment by Geobert** [comment]
ah zut ^^ bon bah faudra un autre bot pour ça alors ^^

/me ajoute un item sur sa TODO list…
