### ISSUE TITLE
Corrections à apporter sur certains personnages

### ISSUE THREAD

**Issue by plumedours** [sin0light/api-kaamelott#3]
Salut, je n'ai pas trouver d'autre moyen pour te contacter. J'ai repéré des manques, notamment pour le personnage Breccan. Il y a bien le nom de l'acteur qui sort (Yvan Le Bolloc'h), mais le nom du personnage sort "null".

Comment faire pour corriger ça ? Est-ce que je peux t'aider et modifier un fichier ? Si je peux, j'essaierai de faire un contrôle global.

**Comment by plumedours** [comment]
Je ne sais pas comment fonctionne les pull request, etc... Mais j'ai vu que dans le fichier quotes.php, il y avait des entrées "NULL".

Pour Yvant Le Bolloch's = Breccan
Pour Anne Girouard = Guenièvre

Ce sont les deux personnages qui posent problème avec le NULL.

Mais comme je ne sais pas comment faire de pull request, j'espère que tu verras ces messages afin de corriger ça. J'aimerai utiliser l'api pour une application :) Merci à toi !

**Comment by sin0light** [comment]
Hello @plumedours,

Merci beaucoup de m'avoir fait remonter ce bug, je viens de le corriger.
Je suis en train de refondre cette API car elle n'est pas très propre mais le travail n'est pas encore terminé !

A+

**Comment by plumedours** [comment]
Salut ! Super, merci. J'aimerai utiliser cette api pour faire une petite
application Android. J'aurai aimé participer pour la remplir de citation,
mais comme je n'y connais rien sur github....

Tu refais l'api, ça veut dire que l'URL va changer, ou les données json ?

**Comment by sin0light** [comment]
Hello @plumedours,

Si tu souhaites participer, tu peux forker le repository (le dupliquer chez toi), ajouter les citations que tu souhaites (en respectant le format actuel (qui est très nul je l'admets)) puis faire ce que l'on appelle une pull request (appliquer les changements que tu as fais sur la copie chez toi sur mon repository "officiel"). Tu as beaucoup de documentation en ligne pour t'aider.

Je ne vais rien changer si ce n'est le code qui tourne derrière. Peut-être que j’inclurai la possibilité pour n'importe qui de proposer de nouvelles citations, c'est une bonne idée.

Sin0light

**Comment by plumedours** [comment]
Salut ! Merci pour les infos, je vais essayer ça quand j'aurai un peu de
temps devant moi ^^ en espérant ne pas tout casser :p
