### ISSUE TITLE
Proposition d'une app Android

### ISSUE THREAD

**Issue by plumedours** [sin0light/api-kaamelott#5]
Salut ! Merci pour les mises à jour, c'est tip top !

J'ai commencé à créer une application mobile (Android), qui utilise ton api. J'aimerai te la présenter, est-ce que je peux envoyer un lien wetransfert ici ? (attention, je ne suis qu'un amateur, je ne code pas, j'ai utilisé Kodular ^^)

Je ne sais pas comment te contacter autrement que par une issue, désolé si ce message n'a rien à faire ici. Si tu souhaite voir ce que j'ai réalisé, tu me dis, je te fais un lien pour télécharger le .apk
Et si tu trouves ça sympa, et que tu as des idées à ajouter, je suis preneur ^^

Merci encore pour cette api et le boulot que tu fais !

Max.

**Comment by sin0light** [comment]
Hello,

Non c'est plus simple par message/mail, je t'ai envoyé un message sur ton site.

Sin0light
