### ISSUE TITLE
Erreur de endpoint dans la doc

### ISSUE THREAD

**Issue by ashk74** [sin0light/api-kaamelott#6]
Hello @sin0light !

J'ai remarqué une petite erreur dans la doc concernant le endpoint de récupération d'un portrait.

En effet le endpoint actuel `GET /all/personnage/:personnage/pic` (ligne 139) retourne une erreur 404.
Pour corriger cela il suffit de le remplacer par `GET /personnage/:personnage/pic` afin de récupérer le portrait en question.

Bonne continuation à toi et merci pour cette API bien fun 😊

**Comment by sin0light** [comment]
Hello @ashk74,

Ha bien vu ! J'ai corrigé la documentation, merci de m'avoir remonté le problème ! 🙂

**Comment by ashk74** [comment]
Pas de soucis 😉
