### ISSUE TITLE
Gestion de la pagination

### ISSUE THREAD

**Issue by atcha** [sin0light/api-kaamelott#7]
Bonjour et merci pour cette API :).
J'aurai voulu savoir si il serait possible /prévu de mettre en place un système de pagination.
Lorsque j'appelle l'API pour récupérer les citations de tout une Livre, ça fait un paquet.
Pourvoir passer un/des query params pour paginer serait super :).

**Comment by sin0light** [comment]
Hello,

Merci à toi pour cette suggestion. Ce n'est pas prévu pour le moment (par manque de temps notamment), mais je pourrais approuver une PR avec plaisir.

Sinolight
