### ISSUE TITLE
Origine des quotes

### ISSUE THREAD

**Issue by Essilu** [sin0light/api-kaamelott#8]
Bonjour, j'aime beaucoup votre API, je voulais savoir comment est-ce que vous avez obtenu les quotes de kaamelott avec leur origine et leurs épisodes. Merci d'avance, et bonne journée

**Comment by sin0light** [comment]
Hello,

La plupart des quotes viennent d'ici : https://fr.wikiquote.org/wiki/Kaamelott
Le reste fait parti d'ajouts manuels etc.

Sin0light
