### ISSUE TITLE
Connexion par JS (Access Control Allow Origin)

### ISSUE THREAD

**Issue by MarKowPowLow** [sin0light/api-kaamelott#9]
Bonjour !

Je suis en formation pour devenir développeur web/web mobile et je cherche à faire une application avec votre API pour afficher soit une citation, soit lancé un son au clic et je n'arrive pas à y parvenir (Pour le moment, j'essaye juste d'avoir accès à l'API). Je ne comprends pas trop comment passé la sécurité. J'ai essayé beaucoup de choses, mais je n'ai plus trop d'idée (Je ne sais pas si vous verrez mon message ou non dans les jours à venir, si oui, merci d'avance ^^).

`let headers =  new Headers()

headers.append('Access-Control-Allow-Origin', 'http://127.0.0.1:5500');
headers.append('Access-Control-Allow-Methods', 'GET')
async function  fetchcall () {
    var data = new URLSearchParams();
    data.append("citation", document.getElementById("citation"));
    data.append("personnage", document.getElementById("personnage"));

try{

    let response = await fetch("https://kaamelott.chaudie.re/api/random", {
        method : "GET",
        mode:"cors",
        headers : headers,
    })
    console.log(response)
}catch(error) {
    console.log(error);
}

return false;
}

addEventListener("click", (e) => {
    e.preventDefault();
    fetchcall();
    })`

**Comment by sin0light** [comment]
Hello,

Je suis désolé mais je ne fais pas de support pour les applications qui utilisent l'API.
Le header Access-Control-Allow-Origin est utilisé côté serveur et tu es côté client dans ce cas, ça ne semble donc pas être la source du problème.

Documentation que je te conseille d'étudier : 
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
- https://www.digitalocean.com/community/tutorials/how-to-use-the-javascript-fetch-api-to-get-data

Sin0light
